name: CI

on:
  push:
    branches: [ improve_github_action ]
  pull_request:
    branches: [ improve_github_action ]

jobs:
  build-server-client:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: luxwheels
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Wait for MySQL to be ready
        run: |
          for i in {120..0}; do
            if echo 'SELECT 1' | mysql -u root -proot -h 127.0.0.1 luxwheels &> /dev/null; then
              break
            fi
            echo 'MySQL is unavailable - sleeping'
            sleep 1
          done
          if [ "$i" = 0 ]; then
            echo 'MySQL did not start up in time'
            exit 1
          fi

      - name: Build and start server
        run: |
          mvn clean install --file LuxWheels/server/pom.xml
          mvn spring-boot:run --file LuxWheels/server/pom.xml &
          sleep 30

      - name: Build client module
        run: mvn clean install --file LuxWheels/client/pom.xml

      - name: Run tests for client module
        env:
          DB_URL: jdbc:mysql://127.0.0.1:3306/luxwheels
          DB_USERNAME: root
          DB_PASSWORD: root
        run: mvn test --file LuxWheels/client/pom.xml

      - name: Run tests for server module
        env:
          DB_URL: jdbc:mysql://127.0.0.1:3306/luxwheels
          DB_USERNAME: root
          DB_PASSWORD: root
        run: mvn test --file LuxWheels/server/pom.xml

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Security analysis with OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check --file LuxWheels/pom.xml

  notify:
    needs: [build-server-client, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Notify build status
        run: echo "Build completed for all jobs"
